import live from "../../../public/live_order.png";
import pos from "../../../public/pos.png";
import kds from "../../../public/kds.png";
import reserve from "../../../public/reserveArtboard.png";
import expense from "../../../public/pettycashArtboard 2.png";
import petty from "../../../public/pettycashArtboard 1.png";
import store from "../../../public/online_store.png";
import table from "../../../public/round-table-white.png";
import alert from "../../../public/notify-round.png";
import avatar from "../../../public/avatar.png";
import toggler from "../../../public/toggle.png";
import folder from "../../../public/folder.png";
import edit from "../../../public/edit.png";
import block from "../../../public/block.png";
import deletebtn from "../../../public/delete-button.png";
import printer from "../../../public/printer.png";
import exportexcel from "../../../public/export-excel.webp";
import exportpdf from "../../../public/export-pdf.webp";
import calendar from "../../../public/calendar.png";
import file from "../../../public/file.png";
import checked from "../../../public/checked.png";
import cross from "../../../public/delete.png";
import zoom from "../../../public/zoom.png";
import editpen from "../../../public/edit-tools.png";
import Sidebar from "../../components/sidebar/Sidebar";

export { live, pos, kds, reserve, expense, petty, store, table, alert, avatar, toggler, folder, edit, block, deletebtn, printer, exportexcel, exportpdf, calendar, file, checked, cross, zoom, editpen, Sidebar };